name: Build Resume and Deploy to Website

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true

      - name: Deploy PDF to personal website repo
        run: |
          git config --global user.name 'soominimini'
          git config --global user.email 'soominimini@naver.com'
          git clone https://github.com/soominimini/soomin.github.io.git website
          cp Resume.pdf website/Resume.pdf
          cd website
          git add Resume.pdf
          git commit -m "Update Resume PDF"
          git push https://x-access-token:${{ secrets.PERSONAL_SITE_TOKEN }}@github.com/soominimini/soomin.github.io.git main
